SUBS 1195 biostudies api changes
EMBL-EBI-SUBS/subs-biostudies-agent pull request #11
Opened 2018-06-15 14:49 UTC by davidrichardson

2018-06-15 15:23 UTC, fpenim requested changes

2018-06-15 15:23 UTC, fpenim commented on src/main/java/uk/ac/ebi/subs/biostudies/converters/UsiSubmissionToDataOwner.java
> +                .name("JohnDoe") //FIXME
To fix

2018-06-15 16:40 UTC, davidrichardson commented
Good catch @fpenim, should be better now

2018-06-18 09:27 UTC, fpenim approved these changes

2018-06-18 09:28 UTC, merged